# Generated by Django 6.0.3 on 2026-03-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('flight', 'seat_number')},
        ),
    ]
