# Generated by Django 6.0.3 on 2026-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reservation_seat_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='identifier',
            field=models.CharField(error_messages={'unique': 'Já existe um avião com este identificador. Por favor, escolha outro.'}, max_length=100, unique=True),
        ),
    ]
