# Generated by Django 6.0.3 on 2026-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contact_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
