# Generated by Django 6.0.3 on 2026-04-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='code',
            new_name='record_locator',
        ),
    ]
